default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost
  port: 5434

development:
  <<: *default
  database: bidderOS_api_development

test:
  <<: *default
  database: bidderOS_api_test

production:
  <<: *default
  database: bidderOS_api_production
  username: bidderOS_api
  password: <%= ENV['BIDDEROS_API_DATABASE_PASSWORD'] %>
