default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: bidderos
  password: password
  host: localhost
  port: 5432

development:
  <<: *default
  database: bidderOS_api_development

test:
  <<: *default
  database: bidderOS_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
